version: '3'
services:
  python3:
    ports:
      - "8888:8888"
    build: .
    container_name: NFT_AI
    working_dir: '/root/'
    tty: true
    volumes:
      - ./code:/root/code
      - ./notebooks:/root/notebooks
      - ./src:/root/src:ro
    environment:
      - JUPYTER_ENABLE_LAB=yes
      - OPENSEA_API_KEY=${OPENSEA_API_KEY}
    command: bash -c "jupyter lab"
